name: Build LuCI ALL packages

on:
  workflow_dispatch:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - version: "23.05"
            sdk_url: "https://downloads.openwrt.org/releases/23.05.6/targets/x86/64/openwrt-sdk-23.05.6-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz"

          - version: "24.10"
            sdk_url: "https://downloads.openwrt.org/releases/24.10.6/targets/x86/64/openwrt-sdk-24.10.6-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst"

          - version: "25.12"
            sdk_url: "https://downloads.openwrt.org/releases/25.12.2/targets/x86/64/openwrt-sdk-25.12.2-x86-64_gcc-14.3.0_musl.Linux-x86_64.tar.zst"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Free space
        run: |
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /opt/ghc || true
          sudo docker system prune -af || true

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y wget rsync build-essential xz-utils zstd

      - name: Download SDK
        run: |
          set -e

          file_name=$(basename "${{ matrix.sdk_url }}")

          wget -O "$file_name" "${{ matrix.sdk_url }}"

          tar -xf "$file_name"

          rm -f *.tar.zst *.tar.xz || true

          sdk_dir=$(find . -maxdepth 1 -type d -name "openwrt-sdk*" | head -n1)

          mv "$sdk_dir" sdk

      - name: Add LuCI package
        run: |
          set -e

          PKG_DIR="sdk/package/custom/luci-app-dnsproxy"

          mkdir -p "$PKG_DIR"

          cp -r ./htdocs "$PKG_DIR/"
          cp -r ./po "$PKG_DIR/"
          cp -r ./root "$PKG_DIR/"
          cp ./Makefile "$PKG_DIR/"

      - name: Update feeds (light)
        run: |
          cd sdk
          ./scripts/feeds update luci
          ./scripts/feeds install -p luci

      - name: Build package
        run: |
          cd sdk
          make package/custom/compile -j$(nproc)

      - name: Collect artifacts
        run: |
          mkdir -p out
          find sdk/bin -type f \( -name "*.ipk" -o -name "*.apk" \) -exec cp {} out/ \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: luci-${{ matrix.version }}
          path: out/*
